# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KBwrkguk5qCvr_NiLYGFDrxqZj7DErsc
"""

import streamlit as st
import pickle

# Load the trained model and vectorizer
with open('spam_model.pkl', 'rb') as f:
    model = pickle.load(f)

with open('tfidf_vectorizer.pkl', 'rb') as f:
    vectorizer = pickle.load(f)

# Streamlit UI
st.set_page_config(page_title="Email Spam Detector", layout="centered")
st.title("📧 Email Spam Detector")

st.markdown("Type an email below and I'll tell you if it's spam or not.")

# Text input
email_text = st.text_area("Enter email content here:")

if st.button("Predict"):
    if email_text.strip() == "":
        st.warning("Please enter some email text.")
    else:
        # Preprocess and predict
        input_vec = vectorizer.transform([email_text])
        prediction = model.predict(input_vec)[0]

        if prediction == 1:
            st.error("🚨 This email is SPAM.")
        else:
            st.success("✅ This email is NOT spam.")